<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6FJLI26U" failures="1" tests="3" name="Test" time="56.934" errors="0" timestamp="2020-05-20T12:36:35 IST">
  <testcase classname="intermediateLevelTests.JQuerySelectDropdownTest" name="JQuerySelectDropdownVerify" time="3.79"/>
  <testcase classname="applicationTests.CheckBoxDemoTest" name="multipleCheckBoxVerify" time="0.95"/>
  <testcase classname="applicationTests.CheckBoxDemoTest" name="singleCheckBoxVerify" time="0.797">
    <failure type="java.lang.AssertionError" message="expected [Success - aaCheck box is checked] but found [Success - Check box is checked]">
      <![CDATA[java.lang.AssertionError: expected [Success - aaCheck box is checked] but found [Success - Check box is checked]
at applicationTests.CheckBoxDemoTest.singleCheckBoxVerify(CheckBoxDemoTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- singleCheckBoxVerify -->
</testsuite> <!-- Test -->
